version: '3.5'

networks:
  common:
    name: 'common'
    driver: bridge

services:
  bl_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - common

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: bl_app_server
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - common
    depends_on:
      - app
